register_keys:
  strict_usb3.0_check: 0
  use_host_ros_time: 0
  streamctrl: 1

  # IMU calibration mode: keep only the raw IMU stream active.
  sendrgb: 0
  sendrgbraw: 0
  sendrgbcompressed: 0
  sendrgbundistort: 0

  sendimu: 1
  enable_imu_smooth: 0
  imu_smooth_frequency: 400

  sendodom: 0
  send_odom_baselink_tf: 0

  senddtof: 0
  cloud_raw_confidence_threshold: 35
  dtof_fps: 100

  sendcloudslam: 0
  sendcloudrender: 0
  senddepth: 0
  sendreprojection: 0
  sendoverlay: 0

  recorddata: 0
  devstatuslog: 0
  save_log: 0
  pubintensitygray: 0
  showpath: 0
  showcamerapose: 0

  custom_map_mode: 0
  custom_init_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
  relocalization_map_abs_path: ""
  mapping_result_dest_dir: ""
  mapping_result_file_name: ""

  sendimagemask: 0
  image_mask_abs_path: ""
  resetalgo: 0
